import "./_reset.css";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<main className="layout_wrapper">
					<Header />
					<div className="main_content">{children}</div>
					<Footer />
				</main>
			</body>
		</html>
	);
}

function Header() {
	return (
		<>
			<header className="header">
				<nav>
					<ul>
						<li>Home</li>
						<li>About</li>
						<li>Blog</li>
						<li>Contact</li>
					</ul>
				</nav>
			</header>
		</>
	);
}

function Footer() {
	return (
		<>
			<footer className="footer">Copyright @2023</footer>
		</>
	);
}
